In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

from sqlalchemy import create_engine
import pymysql

%matplotlib inline

## Art Recommender

### 1. Load Data

In [2]:
sqlEngine       = create_engine('mysql+pymysql://root:sabrina_art@127.0.0.1:3301/sabrina_art')
dbConnection    = sqlEngine.connect()

### 2. Create Feature Set

In [3]:
features_source = pd.read_sql("select artwork_id, gene_id from artworks_to_genes", dbConnection)
features_source["rating"] = 1
artFeatures = features_source.pivot_table(columns="gene_id",index="artwork_id",values="rating").fillna(0)
artFeatures.head(10)

gene_id                   4d90d18edcdd5f44a500000d  4d90d18edcdd5f44a500000f  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       0.0                       0.0   
4d8b92ee4eb68a1b2c0009ab                       0.0                       0.0   
4d8b93394eb68a1b2c0010fa                       0.0                       0.0   
4d8b937c4eb68a1b2c001722                       0.0                       0.0   
4d8b93b04eb68a1b2c001b9d                       0.0                       0.0   
4eaeecc3d2a5820001006e93                       0.0                       0.0   
4eaeedd66899c800010066ac                       0.0                       0.0   
4eaef38fec5cf6000100a3f9                       0.0                       0.0   
4eaefa6c76e78f0001009d40                       0.0                       0.0   
4eaefc4976e78f0001009e86                       0.0                       0.0   

gene_id                   4d90d18edcdd5f44a5000010  4d90d18edcdd5f44a5000012  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       1.0                       0.0   
4d8b92ee4eb68a1b2c0009ab                       1.0                       0.0   
4d8b93394eb68a1b2c0010fa                       1.0                       0.0   
4d8b937c4eb68a1b2c001722                       1.0                       0.0   
4d8b93b04eb68a1b2c001b9d                       1.0                       0.0   
4eaeecc3d2a5820001006e93                       1.0                       0.0   
4eaeedd66899c800010066ac                       1.0                       0.0   
4eaef38fec5cf6000100a3f9                       1.0                       0.0   
4eaefa6c76e78f0001009d40                       1.0                       0.0   
4eaefc4976e78f0001009e86                       1.0                       0.0   

gene_id                   4d90d18edcdd5f44a5000013  4d90d18fdcdd5f44a5000016  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       0.0                       0.0   
4d8b92ee4eb68a1b2c0009ab                       0.0                       0.0   
4d8b93394eb68a1b2c0010fa                       0.0                       0.0   
4d8b937c4eb68a1b2c001722                       0.0                       0.0   
4d8b93b04eb68a1b2c001b9d                       0.0                       0.0   
4eaeecc3d2a5820001006e93                       0.0                       0.0   
4eaeedd66899c800010066ac                       0.0                       0.0   
4eaef38fec5cf6000100a3f9                       0.0                       0.0   
4eaefa6c76e78f0001009d40                       0.0                       0.0   
4eaefc4976e78f0001009e86                       0.0                       0.0   

gene_id                   4d90d18fdcdd5f44a5000025  4d90d18fdcdd5f44a500002c  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       0.0                       0.0   
4d8b92ee4eb68a1b2c0009ab                       0.0                       0.0   
4d8b93394eb68a1b2c0010fa                       0.0                       0.0   
4d8b937c4eb68a1b2c001722                       0.0                       0.0   
4d8b93b04eb68a1b2c001b9d                       0.0                       0.0   
4eaeecc3d2a5820001006e93                       0.0                       0.0   
4eaeedd66899c800010066ac                       0.0                       0.0   
4eaef38fec5cf6000100a3f9                       0.0                       0.0   
4eaefa6c76e78f0001009d40                       0.0                       0.0   
4eaefc4976e78f0001009e86                       0.0                       0.0   

gene_id                   4d90d18fdcdd5f44a500002e  4d90d190dcdd5f44a5000031  \
artwork_id                                                                  

In [4]:
with open("/Users/sabrinarubert/Git/artRecommender/00_Data/artFeatures.pkl","wb") as mf:
    pickle.dump(artFeatures, mf, protocol=pickle.HIGHEST_PROTOCOL)

### 3. Modelling

In [5]:
from scipy.sparse import csr_matrix

In [6]:
mat_artFeatures = csr_matrix(artFeatures)

### 3.1 Train KNN (K-Nearest-Neighbors)

In [7]:
from sklearn.neighbors import NearestNeighbors

In [8]:
model_knn = NearestNeighbors(metric="cosine",
                             algorithm="brute",
                             n_jobs=-1)
model_knn.fit(mat_artFeatures)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=-1, n_neighbors=5, p=2, radius=1.0)

In [9]:
with open("/Users/sabrinarubert/Git/artRecommender/00_Data/artFeatures.pkl","wb") as mk:
    pickle.dump(model_knn, mk, protocol=pickle.HIGHEST_PROTOCOL)

In [10]:
artFeatures.head()

gene_id                   4d90d18edcdd5f44a500000d  4d90d18edcdd5f44a500000f  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       0.0                       0.0   
4d8b92ee4eb68a1b2c0009ab                       0.0                       0.0   
4d8b93394eb68a1b2c0010fa                       0.0                       0.0   
4d8b937c4eb68a1b2c001722                       0.0                       0.0   
4d8b93b04eb68a1b2c001b9d                       0.0                       0.0   

gene_id                   4d90d18edcdd5f44a5000010  4d90d18edcdd5f44a5000012  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       1.0                       0.0   
4d8b92ee4eb68a1b2c0009ab                       1.0                       0.0   
4d8b93394eb68a1b2c0010fa                       1.0                       0.0   
4d8b937c4eb68a1b2c001722                       1.0                       0.0   
4d8b93b04eb68a1b2c001b9d                       1.0                       0.0   

gene_id                   4d90d18edcdd5f44a5000013  4d90d18fdcdd5f44a5000016  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       0.0                       0.0   
4d8b92ee4eb68a1b2c0009ab                       0.0                       0.0   
4d8b93394eb68a1b2c0010fa                       0.0                       0.0   
4d8b937c4eb68a1b2c001722                       0.0                       0.0   
4d8b93b04eb68a1b2c001b9d                       0.0                       0.0   

gene_id                   4d90d18fdcdd5f44a5000025  4d90d18fdcdd5f44a500002c  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       0.0                       0.0   
4d8b92ee4eb68a1b2c0009ab                       0.0                       0.0   
4d8b93394eb68a1b2c0010fa                       0.0                       0.0   
4d8b937c4eb68a1b2c001722                       0.0                       0.0   
4d8b93b04eb68a1b2c001b9d                       0.0                       0.0   

gene_id                   4d90d18fdcdd5f44a500002e  4d90d190dcdd5f44a5000031  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       1.0                       0.0   
4d8b92ee4eb68a1b2c0009ab                       0.0                       0.0   
4d8b93394eb68a1b2c0010fa                       0.0                       0.0   
4d8b937c4eb68a1b2c001722                       0.0                       0.0   
4d8b93b04eb68a1b2c001b9d                       0.0                       0.0   

gene_id                   ...  56539404ebad647f5493ac0f  \
artwork_id                ...                             
4d8b92eb4eb68a1b2c000968  ...                       1.0   
4d8b92ee4eb68a1b2c0009ab  ...                       0.0   
4d8b93394eb68a1b2c0010fa  ...                       0.0   
4d8b937c4eb68a1b2c001722  ...                       0.0   
4d8b93b04eb68a1b2c001b9d  ...                       1.0   

gene_id                   56539ab1ebad6425e9000020  566069979c18db2a45000137  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       0.0                       0.0   
4d8b92ee4eb68a1b2c0009ab                       0.0                       0.0   
4d8b93394eb68a1b2c0010fa                       0.0                       0.0   
4d8b937c4eb68a1b2c001722                       0.0                       0.0   
4d8b93b04eb68a1b2c001b9d                       0.0                       0.0   

gene_id                   56a69bcf139b21066b000385  56c337486428707983000236  \
artwork_id                                                                     
4d8b92eb4eb68a1b2c000968                       0.0          

In [11]:
#artFeatures.loc[1].values.reshape(1, -1)
artFeatures.loc["4eaef38fec5cf6000100a3f9"].values.reshape(1, -1)

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 

In [12]:
model_knn.kneighbors(artFeatures.loc["4eaef38fec5cf6000100a3f9"].values.reshape(1, -1), n_neighbors=6)

(array([[0.        , 0.31400566, 0.34920863, 0.37377571, 0.37377571,
         0.37377571]]),
 array([[  7, 494,  15, 150, 121, 257]]))

In [13]:
artFeatures.iloc[494]

gene_id
4d90d18edcdd5f44a500000d    0.0
4d90d18edcdd5f44a500000f    0.0
4d90d18edcdd5f44a5000010    1.0
4d90d18edcdd5f44a5000012    0.0
4d90d18edcdd5f44a5000013    0.0
                           ... 
56c337b0a09a673f87000254    0.0
56c611fa4b848066ee00005c    0.0
573a4823cb4c274cf800078a    0.0
577ff0889c18db0a00000029    0.0
579693ae7076d00685000594    0.0
Name: 508175534b42ad0002000df0, Length: 507, dtype: float64

In [14]:
artFeatures.iloc[15]

gene_id
4d90d18edcdd5f44a500000d    0.0
4d90d18edcdd5f44a500000f    0.0
4d90d18edcdd5f44a5000010    1.0
4d90d18edcdd5f44a5000012    0.0
4d90d18edcdd5f44a5000013    0.0
                           ... 
56c337b0a09a673f87000254    0.0
56c611fa4b848066ee00005c    0.0
573a4823cb4c274cf800078a    0.0
577ff0889c18db0a00000029    0.0
579693ae7076d00685000594    0.0
Name: 4eaf1910bddaf7000100d117, Length: 507, dtype: float64

In [15]:
artFeatures.iloc[150]

gene_id
4d90d18edcdd5f44a500000d    0.0
4d90d18edcdd5f44a500000f    0.0
4d90d18edcdd5f44a5000010    1.0
4d90d18edcdd5f44a5000012    0.0
4d90d18edcdd5f44a5000013    0.0
                           ... 
56c337b0a09a673f87000254    0.0
56c611fa4b848066ee00005c    0.0
573a4823cb4c274cf800078a    0.0
577ff0889c18db0a00000029    0.0
579693ae7076d00685000594    0.0
Name: 4f9b033d51d0480001000bbd, Length: 507, dtype: float64

In [16]:
artFeatures.iloc[257]

gene_id
4d90d18edcdd5f44a500000d    0.0
4d90d18edcdd5f44a500000f    0.0
4d90d18edcdd5f44a5000010    1.0
4d90d18edcdd5f44a5000012    0.0
4d90d18edcdd5f44a5000013    0.0
                           ... 
56c337b0a09a673f87000254    0.0
56c611fa4b848066ee00005c    0.0
573a4823cb4c274cf800078a    0.0
577ff0889c18db0a00000029    0.0
579693ae7076d00685000594    0.0
Name: 5035a0ee6cb8020002000750, Length: 507, dtype: float64

In [17]:
artFeatures.iloc[121]

gene_id
4d90d18edcdd5f44a500000d    0.0
4d90d18edcdd5f44a500000f    0.0
4d90d18edcdd5f44a5000010    1.0
4d90d18edcdd5f44a5000012    0.0
4d90d18edcdd5f44a5000013    0.0
                           ... 
56c337b0a09a673f87000254    0.0
56c611fa4b848066ee00005c    0.0
573a4823cb4c274cf800078a    0.0
577ff0889c18db0a00000029    0.0
579693ae7076d00685000594    0.0
Name: 4eb83745f8b5270001008674, Length: 507, dtype: float64

### 4. Making the Art Recommender more user-friendly

#### 4.1 Translate model output (recommendations) to artwork titles

In [28]:
distances, indices = model_knn.kneighbors(artFeatures.loc["4eaef38fec5cf6000100a3f9"].values.reshape(1, -1), n_neighbors=6)

In [29]:
indices

array([[  7, 494,  15, 150, 121, 257]])

In [30]:
artworkList = pd.read_sql("select id as artwork_id, title as artwork_title from artworks", dbConnection)

In [31]:
artworkList

artwork_id  \
0      4d8b92eb4eb68a1b2c000968   
1      4d8b92ee4eb68a1b2c0009ab   
2      4d8b93394eb68a1b2c0010fa   
3      4d8b937c4eb68a1b2c001722   
4      4d8b93b04eb68a1b2c001b9d   
...                         ...   
37652  59cd2a4f139b2121047df82d   
37653  59cd2bf39c18db4a6bf67e9d   
37654  59cd2c78cd530e67ac81cd6c   
37655  59cd2da1139b2121047dfa12   
37656  59cd2e4b7622dd73eb85e2c9   

                                           artwork_title  
0                                    Der Kuss (The Kiss)  
1                                       The Third of May  
2      The Company of Frans Banning Cocq and Willem v...  
3                                              Mona Lisa  
4        Luncheon on the Grass (Le Déjeuner sur l'herbe)  
...                                                  ...  
37652                                        The Thinker  
37653                                        The Tempest  
37654  Pair of Standing Nude Male Figures Demonstrati...  
37655                                The Shepherd's Song  
37656                                            Inferno  

[37657 rows x 2 columns]

In [22]:
artworkList.drop_duplicates().sort_values("artwork_id").reset_index(drop=True)

artwork_id  \
0      4d8b92eb4eb68a1b2c000968   
1      4d8b92ee4eb68a1b2c0009ab   
2      4d8b93394eb68a1b2c0010fa   
3      4d8b937c4eb68a1b2c001722   
4      4d8b93b04eb68a1b2c001b9d   
...                         ...   
27572  59cd2a4f139b2121047df82d   
27573  59cd2bf39c18db4a6bf67e9d   
27574  59cd2c78cd530e67ac81cd6c   
27575  59cd2da1139b2121047dfa12   
27576  59cd2e4b7622dd73eb85e2c9   

                                           artwork_title  
0                                    Der Kuss (The Kiss)  
1                                       The Third of May  
2      The Company of Frans Banning Cocq and Willem v...  
3                                              Mona Lisa  
4        Luncheon on the Grass (Le Déjeuner sur l'herbe)  
...                                                  ...  
27572                                        The Thinker  
27573                                        The Tempest  
27574  Pair of Standing Nude Male Figures Demonstrati...  
27575                                The Shepherd's Song  
27576                                            Inferno  

[27577 rows x 2 columns]

In [32]:
artworkList.iloc[7]

artwork_id        4eaef38fec5cf6000100a3f9
artwork_title    The Calling of St Matthew
Name: 7, dtype: object

In [33]:
with open("/Users/sabrinarubert/Git/artRecommender/00_Data/artworkList.pkl", "wb") as ml:
    pickle.dump(artworkList, ml, protocol=pickle.HIGHEST_PROTOCOL)

In [34]:
indices.flatten()

array([  7, 494,  15, 150, 121, 257])

In [35]:
for i, j in enumerate(indices.flatten()):
    artwork = artworkList.iloc[j]
    title = artworkList["artwork_title"]
    if i == 0:
        print(f"Recommendations for {title}:")
        print("-----------------------------------------\n")
    else:
        print(f"{i}: {title}")

Recommendations for 0                                      Der Kuss (The Kiss)
1                                         The Third of May
2        The Company of Frans Banning Cocq and Willem v...
3                                                Mona Lisa
4          Luncheon on the Grass (Le Déjeuner sur l'herbe)
                               ...                        
37652                                          The Thinker
37653                                          The Tempest
37654    Pair of Standing Nude Male Figures Demonstrati...
37655                                  The Shepherd's Song
37656                                              Inferno
Name: artwork_title, Length: 37657, dtype: object:
-----------------------------------------

1: 0                                      Der Kuss (The Kiss)
1                                         The Third of May
2        The Company of Frans Banning Cocq and Willem v...
3                                                Mona Lis